registrySecretName: my-docker-secret

replicaCount: 2
weatherApp:
  image:
    repository: yossizxc/weather
    pullPolicy: IfNotPresent
    tag: 3.3.0.222
  service:
    type: LoadBalancer
    port: 80
    targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi


serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
