apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pod
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pod
      annotations:
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "my-app"
        kube-monkey/kill-mode: "random"
        kube-monkey/kill-value: "100"
    spec:
      containers:
        - name: pod
          image: {{ .Values.weatherApp.image.repository }}:{{ .Values.weatherApp.image.tag }}
          imagePullPolicy: {{ .Values.weatherApp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.weatherApp.service.targetPort }}
          resources:
              requests:
                cpu: {{ .Values.resources.requests.cpu  }}
                memory: {{ .Values.resources.requests.memory  }}
              limits:
                cpu: {{ .Values.resources.limits.cpu  }}
                memory: {{ .Values.resources.limits.memory  }}
          env:
            - name: BG_COLOR
              valueFrom:
                configMapKeyRef:
                  name: configmap-blue
                  key: BG_COLOR
