apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-weather-app
spec:
  selector:
    app: {{ .Release.Name }}-weather-app
  ports:
      - protocol: TCP
        port: {{ .Values.weatherApp.service.port }}
        targetPort: {{ .Values.weatherApp.service.targetPort }}
  type: {{ .Values.weatherApp.service.type }}
